name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint:check

      - name: Run tests
        run: npm run test
