name: pr

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-title:
    runs-on: ubuntu-latest

    name: Validate PR title
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          token: ${{ secrets.PULL_REQUEST_STATS_TOKEN }}
